### ISSUE TITLE
Zendesk Java Client issues working on Google Cloud

### ISSUE THREAD

**Issue by grembek** [cloudbees/zendesk-java-client#167]
Hi,

I am using the Zendesk java client on my Google Cloud server and I have a runtime issue that prevents me from using the SDK. Can you please advise:

When I call zd.getTickets(), I get on the server:
```
Uncaught exception from servlet java.lang.ClassCastException: com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.createUrlConnection(JDKAsyncHttpProvider.java:184)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:147)
	at com.ning.http.client.providers.jdk.JDKAsyncHttpProvider.execute(JDKAsyncHttpProvider.java:118)
	at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:506)
	at org.zendesk.client.v2.Zendesk.submit(Zendesk.java:1751)
	at org.zendesk.client.v2.Zendesk.access$1300(Zendesk.java:90)
```

**Comment by johnou** [comment]
Might be resolved with https://github.com/cloudbees/zendesk-java-client/pull/176

**Comment by johnou** [comment]
Feel free to try master branch, I don't have access to Google Cloud server.
