### ISSUE TITLE
java.lang.NoSuchFieldError: PERMANENT_REDIRECT with zendesk-java-client-0.6.2

### ISSUE THREAD

**Issue by macprovence** [cloudbees/zendesk-java-client#242]
Hi,

I am actually trying to use that zendesk-java-client-0.6.2 using NetBeans.

Just wrote a little prog to connect to zendesk. However i am facing that following error.

Exception in thread "main" java.lang.NoSuchFieldError: PERMANENT_REDIRECT
        at org.asynchttpclient.util.HttpConstants$ResponseStatusCodes.<clinit>(H
ttpConstants.java:47)
        at org.asynchttpclient.netty.handler.intercept.Redirect30xInterceptor.<c
linit>(Redirect30xInterceptor.java:53)
        at org.asynchttpclient.netty.handler.intercept.Interceptors.<init>(Inter
ceptors.java:51)
        at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.<init>(Async
HttpClientHandler.java:59)
        at org.asynchttpclient.netty.handler.HttpHandler.<init>(HttpHandler.java
:38)
        at org.asynchttpclient.netty.channel.ChannelManager.configureBootstraps(
ChannelManager.java:208)
        at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpCli
ent.java:91)
        at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpCli
ent.java:71)
        at org.zendesk.client.v2.Zendesk.<init>(Zendesk.java:139)
        at org.zendesk.client.v2.Zendesk.<init>(Zendesk.java:93)
        at org.zendesk.client.v2.Zendesk$Builder.build(Zendesk.java:2507)
....

I am using the following libraries:

zendesk-java-client-0.6.2
async-http-client-2.2.0
jackson-annotations-2.9.4
jackson-core-2.9.3
jackson-databind-2.9.4
netty-all-4.1.9.Final
reactive-streams-1.0.2
slf4j-api-1.7.25
slf4j-jdk14-1.7.25

has anyone of you guies, an idea?

I did not find online any docs indicating which libraries to use.

thx a lot for any help

Regards

Romuald

**Comment by johnou** [comment]
netty-all-4.1.9.Final is probably too old, async-http-client versions should match the Netty version they were compiled with eg. async-http-client 2.3.0 and netty 4.1.21.Final.
