### ISSUE TITLE
Request Timeout to xxx.zendesk.com/35.174.160.246:443 after 60000 ms

### ISSUE THREAD

**Issue by RobertBTDM** [cloudbees/zendesk-java-client#269]
Hello,

i've got problems with creating a ticket via the Java ZenDesk API.
I create an new instance of the ZenDesk class with the params username und token.

In the API settings tab of the ZenDesk HelpCenter site i can see that the token was used seconds ago, but i can't `post` a new ticket.

I use the method createTicket() of the instantiated ZenDesk.

The Firewall is configurated to allow traffic over all ports.

```
            Ticket t = new Ticket(
                    new Ticket.Requester(config.getProperty("requester.name"), config.getProperty("requester.email")),
                    "This is a test " + UUID.randomUUID().toString(), new Comment("Please ignore this ticket"));
            ticket = this.instance.createTicket(t);
```

StackTrace:

```
org.zendesk.client.v2.ZendeskException: java.util.concurrent.TimeoutException: Request timeout to motorolambp.zendesk.com/35.174.158.178:443 after 60000 ms
	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2239)
	at org.zendesk.client.v2.Zendesk.createTicket(Zendesk.java:306)
	at org.zendesk.client.v2.RealSmokeTest.createSolveTickets(RealSmokeTest.java:382)
	at test.ZenDeskClientTest.main(ZenDeskClientTest.java:17)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Request timeout to motorolambp.zendesk.com/35.174.158.178:443 after 60000 ms
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:202)
	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2226)
	... 3 more
Caused by: java.util.concurrent.TimeoutException: Request timeout to motorolambp.zendesk.com/35.174.158.178:443 after 60000 ms
	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43)
	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
```

I used the RealSmokeTest.java for my testing purposes.

What can be the problem?

**Comment by aheritier** [comment]
Hi @RobertBTDM 

  I got some similar errors recently in different types of calls. I don't really explain them for now. I have the feeling that Zendesk is sometimes slow to handle APIs calls. 

  What you can try is to increase the timeout. For this you have to many create a `DefaultAsyncHttpClient` with a longer timeout and then you use the `setClient` method from `Zendesk.Builder`

BR

**Comment by RobertBTDM** [comment]
Hi @aheritier 

thanks for your answer!

I've set the timeout like you described, but i got the same error message with the same timeout (60000ms).

```
		DefaultAsyncHttpClientConfig cfg = new DefaultAsyncHttpClientConfig.Builder()
				.setRequestTimeout(100000)
				.setConnectTimeout(100000)
				.setSslSessionTimeout(Integer.valueOf(100000))
				.setHandshakeTimeout(100000)
				.setShutdownTimeout(100000)
				.setReadTimeout(100000)
				.setPooledConnectionIdleTimeout(100000)
				.build();
		AsyncHttpClient ahc = new DefaultAsyncHttpClient(cfg);

		this.instance = new Zendesk.Builder(config.getProperty("url"))
				.setUsername(config.getProperty("username"))
				.setToken(config.getProperty("token"))
				.setClient(ahc)
				.build();
```

**Comment by RobertBTDM** [comment]
Sorry, my fault.

The Error Message was the same, but with different timeout (in my example 100000ms instead of 60000ms)

**Comment by RobertBTDM** [comment]
at this point, i get the timeout exception.

![error_message](https://user-images.githubusercontent.com/43168655/45362100-33b51600-b5d4-11e8-9153-13ad5eb94bfc.png)

**Comment by aheritier** [comment]
and on the zendesk side -> APIs do you see your user doing some calls ?
It's strange that you get no answer at all
What happens if you try with a very long timeout like 10 minutes ?

**Comment by RobertBTDM** [comment]
yes, on the api side i can see there was 1 or 2 calls, depending on the runs with my java application.

It's very strange, because i tried it with php API for Zen Desk and it works fine, even with the first try in just 1 or 2 seconds.

I will try it with 10 minutes, but i don't think it will help...

**Comment by RobertBTDM** [comment]
I tested it with 10 minutes without success.

**Comment by aheritier** [comment]
it's strange. You are using the latest release ?
I don't really see how to diagnose this because the problem is clearly zendesk which isn't sending back an answer. Maybe you can activate the debugging logs for HAC but I'm not sure we'll see something.

**Comment by RobertBTDM** [comment]
i found my problem.

i used the wrong external jars like netty utils and so on.

No it works with a correct response, without timeout an error message.

thanks for your help!

**Comment by RobertBTDM** [comment]
Thanks!

it was a bit difficult but the slf4j logger helped me a lot.
