### ISSUE TITLE
Add new mandatory fields to the Article model

### ISSUE THREAD

**Issue by Dohbedoh** [cloudbees/zendesk-java-client#289]
**Describe the bug**

Recent changes to the Zendesk API requires that the fields `user_segment_id ` and `permission_group_id` be set to an Article to be able to create it. See:

* https://develop.zendesk.com/hc/en-us/articles/360001934168
* https://developer.zendesk.com/rest_api/docs/help_center/articles#create-article

**To Reproduce**

Create a test case against a Zendesk environment that create a real simple article like the following:

```
        Article article = new Article();
        article.setSectionId(123456789L);
        article.setAuthorId(instance.getAuthenticatedUser().getId());
        article.setTitle("[Test] from zendesk-java-client");
        instance.createArticle(article);
```

**Expected behavior**

We would expect the article to be created without any issue.

**Actual behavior**

The article is not created because of the exception:

```
org.zendesk.client.v2.ZendeskResponseException: HTTP/400: Bad Request - {"title":"Invalid attribute","message":"You passed an invalid value for the user_segment_id attribute. You must provide user_segment_id. Set to 'null' to make it visible to everyone.. You passed an invalid value for the permission_group_id attribute. You must provide permission_group_id."}

	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2252)
	at org.zendesk.client.v2.Zendesk.createArticle(Zendesk.java:1666)
	at org.zendesk.client.v2.RealArticleCreationTest.createArticleWithoutSegments(RealArticleCreationTest.java:76)
	[...]
Caused by: org.zendesk.client.v2.ZendeskResponseException: HTTP/400: Bad Request - {"title":"Invalid attribute","message":"You passed an invalid value for the user_segment_id attribute. You must provide user_segment_id. Set to 'null' to make it visible to everyone.. You passed an invalid value for the permission_group_id attribute. You must provide permission_group_id."}
	at org.zendesk.client.v2.Zendesk$BasicAsyncCompletionHandler.onCompleted(Zendesk.java:1997)
	[...]    
```

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: OSX 10.14.5 (also reproduced from Alpine 3.9)
 - Browser: Chrome
 - Version zendesk-java-client-0.8.0

**Additional context**

This is related to a change in the Articles API, downstream of the new Zendesk Guide permissions solution: https://develop.zendesk.com/hc/en-us/articles/360001934168

**Comment by aheritier** [comment]
Pr merged @Dohbedoh
