### ISSUE TITLE
Fix test failure org.zendesk.client.v2.RealSmokeTest.getArticleTranslations

### ISSUE THREAD

**Issue by aheritier** [cloudbees/zendesk-java-client#309]
The issue is

```
Tests run: 53, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 144.102 sec <<< FAILURE! - in org.zendesk.client.v2.RealSmokeTest
getArticleTranslations(org.zendesk.client.v2.RealSmokeTest)  Time elapsed: 1.64 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at org.zendesk.client.v2.RealSmokeTest.getArticleTranslations(RealSmokeTest.java:862)
```

**Comment by aheritier** [comment]
body is not mandatory <https://developer.zendesk.com/rest_api/docs/help_center/translations.html>

We did the same fix for `getSectionTranslations` and `getCategoryTranslations` before. 
Not sure why it wasn't already failing for `getArticleTranslations`
