### ISSUE TITLE
Http 400/Bad Request while iterating through tickets.

### ISSUE THREAD

**Issue by btpnlsl** [cloudbees/zendesk-java-client#341]
**Describe the bug**

The Zendesk `PagedIterator.hasNext` method is throwing a ZendeskResponseException with an error code of 400/BAD_REQUEST { error: "ReadOnlyRecord", description: "Requested record cannot be altered"} when iterating through the list of tickets returned from `Zendesk.getTicketsIncrementally(Date startTime)`

The code essentially looks like this:
`Iterable<Ticket> tickets = zendeskAccessor.getTicketsIncrementally(date);`
 `for(Ticket ticket : tickets) {`
 `  ...`
 `}`

I am using version 0.8 of the ZenDesk Java Client. I looked at the code for the client on GitHub and didn't see any relevant changes from version 0.8 -> 0.12.

**To Reproduce**
I'm unsure exactly how to reproduce this behavior, but from the error code I would guess that one of the tickets in the paged list must be read only

**Expected behavior**
I did not expect to see an BAD REQUEST exception while iterating through the list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
Here are the relevant stack traces for the exception:
`org.zendesk.client.v2.ZendeskResponseException: HTTP/400: Bad Request - 
{
    "error": "ReadOnlyRecord",
    "description": "Requested record cannot be altered"
}

	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2246) ~[zendesk-java-client-0.8.0.jar:?]
	at org.zendesk.client.v2.Zendesk.access$1400(Zendesk.java:95) ~[zendesk-java-client-0.8.0.jar:?]
	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2482) ~[zendesk-java-client-0.8.0.jar:?]`

`Caused by: org.zendesk.client.v2.ZendeskResponseException: HTTP/400: Bad Request - 
{
    "error": "ReadOnlyRecord",
    "description": "Requested record cannot be altered"
}

	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:2062) ~[zendesk-java-client-0.8.0.jar:?]
	at org.zendesk.client.v2.Zendesk$PagedAsyncListCompletionHandler.onCompleted(Zendesk.java:2040) ~[zendesk-java-client-0.8.0.jar:?]
	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:66) ~[async-http-client-2.3.0.jar:?]
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:223) ~[async-http-client-2.3.0.jar:?]
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:258) ~[async-http-client-2.3.0.jar:?]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:239) ~[async-http-client-2.3.0.jar:?]
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:113) ~[async-http-client-2.3.0.jar:?]
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:142) ~[async-http-client-2.3.0.jar:?]
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:76) ~[async-http-client-2.3.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[netty-codec-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[netty-codec-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486) ~[netty-handler-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235) ~[netty-handler-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282) ~[netty-handler-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[netty-codec-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[netty-codec-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
	... 1 more`

**Comment by aheritier** [comment]
Hi @btpnlsl 

  Did it work previously ? Did you do any change in your code which could be the root cause of this behavior or it's something new which is happening recently ?

  I am using the same kind of code and it was working in the past (I didn't test it recently). Maybe Zendesk Changed something in their side and it is impacting us (not the 1st time).

  What are you doing with the tickets in the loop ? The error `Requested record cannot be altered` let me think that you could try to modify/save the tickets and the api does not allow it. In my code I am using these methods to load the tickets but I don't edit them. Not sure if it could be an limitation (recent or not)

Arnaud

**Comment by btpnlsl** [comment]
Hi Arnaud,

Thanks for responding.  The code has been working previously and is still working most of the time.

The code within the loop is not actually modifying the tickets.  It queries a bunch of properties on each ticket (Id, status, user, updatedAt, customFields), but it never actually modifies the tickets.

The exception is actually being thrown from within the Zendesk PagedIterator code when it is making a call to the Zendesk REST API here: 

[List<T> values = complete(submit(req("GET", nextPage), handler));](https://github.com/cloudbees/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L2831)

It looks like this is related to the Zendesk REST API which is documented here: [https://developer.zendesk.com/rest_api/docs/support/incremental_export#exporting-tickets](https://developer.zendesk.com/rest_api/docs/support/incremental_export#exporting-tickets)

I browsed through the Zendesk REST API documentation on their developer portal but didn't see anything that would be related to that specific error.  I think you are correct that this sounds like something that has either changed in the REST API, or is not documented well.

I am going to look into enabling SLF4J logging to see if I can figure out the specific URL which is called that is giving the error.

**Comment by aheritier** [comment]
Thanks @btpnlsl 
Let us know if you can have more details with some debug logs.
I will verify on my side if I have the problem too. For now I don't think so but with zendesk, everything is possible.

**Comment by btpnlsl** [comment]
Hi @aheritier 

I hit a repro of this exception with debug logging on the Zendesk Client, but unfortunately it don't think its going to provide much useful information.

Here's what I have from the logs:
`[DEBUG] 2020-05-14 06:20:00.161 [pool-4-thread-5] org.zen.cli.v2.Zendesk - Request GET https://omnidian.zendesk.com/api/v2/incremental/tickets.json?start_time=1589439600`
`DEBUG] 2020-05-14 06:20:00.453 [AsyncHttpClient-3-3] org.zen.cli.v2.Zendesk - Response HTTP/400 Bad Request`
`{
    "error": "ReadOnlyRecord",
    "description": "Requested record cannot be altered"
}`
`[ERROR] 2020-05-14 06:20:00.455 [pool-4-thread-5] com.omn.ass.con.ZendeskController - Catching`
`org.zendesk.client.v2.ZendeskResponseException: HTTP/400: Bad Request - 
{
    "error": "ReadOnlyRecord",
    "description": "Requested record cannot be altered"
}`
`	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2246) ~[zendesk-java-client-0.8.0.jar:?]`
`	at org.zendesk.client.v2.Zendesk.access$1400(Zendesk.java:95) ~[zendesk-java-client-0.8.0.jar:?]`
`	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2482) ~[zendesk-java-client-0.8.0.jar:?]`

Based on the sequence of logs it looks like the exception occurs on the initial call to readNext to get the first page of tickets.

I attempted to call the REST API from the logs directly using Postman and did not encounter an error.

I am thinking that this looks like an error on Zendesk's side rather than the client, so I think I will try to engage with them to see if they have any insight.

**Comment by btpnlsl** [comment]
Just an additional followup on this.  It looks like this is an issue that multiple people are seeing over a variety of Zendesk REST APIs.  Here is the discussion thread at Zendesk's community forum:
[https://develop.zendesk.com/hc/en-us/community/posts/360044009813-GET-request-ReadOnlyRecord-Requested-record-cannot-be-altered-](https://develop.zendesk.com/hc/en-us/community/posts/360044009813-GET-request-ReadOnlyRecord-Requested-record-cannot-be-altered-)

**Comment by aheritier** [comment]
arghhh thanks a lot for the feedback @btpnlsl 
I hope they will solve the issue ASAP
