### ISSUE TITLE
Potential bug in getOrganizationUsers

### ISSUE THREAD

**Issue by larsbard** [cloudbees/zendesk-java-client#45]
Hi. 

When calling Zendesk.getOrganizationUsers() I get the following stacktrace: 
java.lang.NoClassDefFoundError: com/damnhandy/uri/template/UriTemplate
	at org.zendesk.client.v2.TemplateUri.<init>(TemplateUri.java:21)
	at org.zendesk.client.v2.Zendesk.tmpl(Zendesk.java:1283)
	at org.zendesk.client.v2.Zendesk.getOrganizationUsers(Zendesk.java:443)

When I look at the implementation, I see that it is implemented different from Zendesk.getUsers()

getUsers() uses cnst, whereas getOrganizationUsers uses tmpl. 

When running curl https://{subdomain}.zendesk.com/api/v2/organizations/{id}/users.json \
  -v -u {email_address}:{password} it returns the expected result.

**Comment by larsbard** [comment]
Solved.

I needed to add the .jar for damnhandy in my lib-folder as I was working with unmanaged dependencies.
